# see https://pyup.io/docs/configuration/ for all available options

schedule: "every month"
update: all
requirements:
  - requirements-doc.txt:
      update: all
  - requirements-test.txt:
      update: all
pr_prefix: "[PyUp] "
