name: Lint check project

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Black Check
        uses: jpetrucciani/black-check@20.8b1
      - name: python-isort
        uses: isort/isort-action@v0.1.0
        with:
          isortVersion: 5.7.0
          configuration: --profile black --diff --check-only
